image: java:8build:
  stage: build
  script:
    - mvn clean package 
test:
  stage: test
  script:
    - bash <(curl -s https://blackducksoftware.github.io/hub-detect/hub-detect.sh) --blackduck.hub.url="${HUB_URL}" --blackduck.hub.api.token="${HUB_TOKEN}" --blackduck.hub.trust.cert=true --detect.policy.check.fail.on.severities=ALL
